using System;
using System.ComponentModel;
using Microsoft.VisualStudio.Shell;
using TSqlFormatter.Configuration;
using TSqlFormatter.Core.Formatting;
using TSqlFormatter.Core.Layout;

namespace TSqlFormatter.VisualStudio;

/// <summary>IDE-local defaults; project configuration can override individual values.</summary>
public sealed class GeneralOptionsPage : DialogPage
{
    private int maxLineLength = 100;
    private int indentSize = 4;

    [Category("General"), DisplayName("Maximum line length")]
    [Description("Preferred maximum width of a formatted SQL line (1–4096).")]
    [DefaultValue(100)]
    public int MaxLineLength
    {
        get => maxLineLength;
        set => maxLineLength = value >= 1 && value <= 4096
            ? value : throw new ArgumentOutOfRangeException(nameof(value), "Use a value from 1 to 4096.");
    }

    [Category("General"), DisplayName("Line ending")]
    [Description("Line ending generated by the formatter.")]
    [DefaultValue(DocLineEnding.Lf)]
    public DocLineEnding LineEnding { get; set; } = DocLineEnding.Lf;

    [Category("General"), DisplayName("Final newline")]
    [Description("Append a newline at the end of formatted SQL.")]
    [DefaultValue(false)]
    public bool FinalNewLine { get; set; }

    [Category("Indent"), DisplayName("Indent size")]
    [Description("Indent width (0–32).")]
    [DefaultValue(4)]
    public int IndentSize
    {
        get => indentSize;
        set => indentSize = value >= 0 && value <= 32
            ? value : throw new ArgumentOutOfRangeException(nameof(value), "Use a value from 0 to 32.");
    }

    [Category("Indent"), DisplayName("Use tabs")]
    [Description("Indent with tabs instead of spaces.")]
    [DefaultValue(false)]
    public bool UseTabs { get; set; }

    [Category("Keywords"), DisplayName("Keyword casing")]
    [Description("Case of generated SQL keywords.")]
    [DefaultValue(KeywordCase.Upper)]
    public KeywordCase KeywordCase { get; set; } = KeywordCase.Upper;

    [Category("Automation"), DisplayName("Format on save")]
    [Description("Off by default. Formats only the active SQL document before saving it; optionally require a project config.")]
    [DefaultValue(SqlSaveFormattingMode.Off)]
    public SqlSaveFormattingMode FormatOnSave { get; set; } = SqlSaveFormattingMode.Off;

    [Category("Automation"), DisplayName("Save exclusions")]
    [Description("Semicolon-separated globs: *.generated.sql; generated/**. A pattern without / matches the file name; a path pattern matches from any directory.")]
    [DefaultValue("")]
    public string SaveExclusions { get; set; } = string.Empty;

    public FormattingOptions CreateOptions() => FormattingOptions.Default.With(
        general: new GeneralOptions(MaxLineLength, LineEnding, FinalNewLine),
        indent: new IndentOptions(IndentSize, UseTabs),
        keywords: new KeywordOptions(KeywordCase));
}
