<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <VSSDKBuildToolsAutoSetup>true</VSSDKBuildToolsAutoSetup>
    <GenerateVsixContainer>true</GenerateVsixContainer>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectCapability Include="CreateVsixContainer" />
    <PackageReference Include="Microsoft.VisualStudio.SDK" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" />
    <Reference Include="System.Design" />
    <VSCTCompile Include="Commands.vsct" />
  </ItemGroup>
</Project>
