<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WarningLevel>8</WarningLevel>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TSqlFormatter.Configuration\TSqlFormatter.Configuration.csproj" />
  </ItemGroup>

</Project>
